[package]
name = "feature_selection"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
linfa = "0.7.1"
linfa-linear = "0.7.1"
ndarray = { version = "0.15", features = ["approx"] }
num_cpus = "1.16.0"
rand = "0.8.5"
